-- Q1. Count sales records per department.
SELECT department,COUNT(*) AS sale_count
FROM employee_sales
GROUP BY department
ORDER BY sale_count DESC;

-- Q2. Calculate total revenue by department.
SELECT department,
       SUM(units*price) AS total_revenue
FROM employee_sales
GROUP BY department
ORDER BY total_revenue DESC;

-- Q3. Find highest and lowest sale value by department.
SELECT department,
       MAX(units*price) AS highest_sale,
       MIN(units*price) AS lowest_sale
FROM employee_sales
GROUP BY department;

-- Q4. Average sale value by department.
SELECT department,
       ROUND(AVG(units*price),2) AS average_sale
FROM employee_sales
GROUP BY department;

-- Q5. Departments with total revenue > 20,000.
SELECT department,SUM(units*price) AS total_revenue
FROM employee_sales
GROUP BY department
HAVING SUM(units*price)>20000
ORDER BY total_revenue DESC;

-- Q6. Departments with at least 3 sales.
SELECT department,COUNT(*) AS sale_count
FROM employee_sales
GROUP BY department
HAVING COUNT(*)>=3;

-- Q7. Filter sales first, then aggregate.
SELECT department,COUNT(*) AS sale_count,AVG(units*price) AS avg_sale
FROM employee_sales
WHERE units>=8
GROUP BY department
ORDER BY sale_count DESC;

-- Q8. Departments with at least 2 sales and average sale > 20,000.
SELECT department,
       COUNT(*) AS sale_count,
       ROUND(AVG(units*price),2) AS avg_sale
FROM employee_sales
GROUP BY department
HAVING COUNT(*)>=2
   AND AVG(units*price)>20000
ORDER BY avg_sale DESC;

-- Q9. Total revenue and average commission by department.
SELECT department,
       ROUND(SUM(units*price),2) AS total_revenue,
       ROUND(AVG(commission),2) AS avg_commission
FROM employee_sales
GROUP BY department
ORDER BY total_revenue DESC;

-- Q10. Number of distinct salespeople by department.
SELECT department,
       COUNT(DISTINCT employee_id) AS salesperson_count
FROM employee_sales
GROUP BY department
ORDER BY salesperson_count DESC;

-- Q11. Departments having at least 2 distinct salespeople.
SELECT department,COUNT(DISTINCT employee_id) AS salesperson_count
FROM employee_sales
GROUP BY department
HAVING COUNT(DISTINCT employee_id)>=2;

-- Q12. Top 2 departments by total revenue.
SELECT department,SUM(units*price) AS total_revenue
FROM employee_sales
GROUP BY department
ORDER BY total_revenue DESC
LIMIT 2;

-- Q13. Interview: name the highest single sale and average sale
-- for departments whose total revenue exceeds 20,000.
SELECT department,
       MAX(units*price) AS highest_sale,
       ROUND(AVG(units*price),2) AS average_sale,
       SUM(units*price) AS total_revenue
FROM employee_sales
GROUP BY department
HAVING SUM(units*price)>20000
ORDER BY total_revenue DESC;

-- Q14. Interview: return departments with total revenue > 20,000
-- and average commission > 900.
SELECT department,
       SUM(units*price) AS total_revenue,
       AVG(commission) AS avg_commission
FROM employee_sales
GROUP BY department
HAVING SUM(units*price)>20000
   AND AVG(commission)>900
ORDER BY total_revenue DESC;

-- Q15. Interview: revenue generated by each salesperson.
SELECT employee_id,
       SUM(units*price) AS total_revenue,
       MAX(units*price) AS highest_sale
FROM employee_sales
GROUP BY employee_id
ORDER BY total_revenue DESC;
